spring.application.name=kanban

spring.datasource.url=jdbc:postgresql://ep-soft-cake-attiu43z-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DZRofPn39sje
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=chave-super-secreta-kanban-2026-trocar-em-producao
jwt.expiration=86400000