spring.application.name=kanban

spring.datasource.url=jdbc:postgresql://ep-soft-cake-attiu43z-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_uBjrxC6aU4Gy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

jwt.secret=uma-chave-secreta-longa-qualquer-pro-dev-local-2026
jwt.expiration=86400000